import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

from graph.state import HiringState

load_dotenv()

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.2,
    api_key=os.getenv("GROQ_API_KEY"),
)


def report_writer_agent(state: HiringState) -> dict:
    """
    Writes the final structured hiring recommendation report.
    """

    # Build a compact candidate summary for the prompt
    candidate_lines = []
    for c in state["all_candidates"]:
        candidate_lines.append(
            f"- {c['name']} | Score: {c['score']}/10 | "
            f"Strengths: {', '.join(c['strengths'][:2])} | "
            f"Gaps: {', '.join(c['gaps'][:2])}"
        )
    candidates_block = "\n".join(candidate_lines)

    shortlist_names = [c["name"] for c in state["shortlisted"]]

    response = llm.invoke([
        SystemMessage(content="""You are an expert HR report writer.
Write a complete hiring recommendation report in markdown.

Structure it EXACTLY like this:

# Hiring Report — [Role Name]

## Executive Summary
[2-3 sentences: how many candidates reviewed, how many shortlisted, top recommendation]

## Role Requirements
- **Required Skills:** [list]
- **Preferred Skills:** [list]
- **Experience:** [X years]

## Candidate Rankings

| Rank | Candidate | Score | Verdict |
|------|-----------|-------|---------|
| 1 | [name] | X/10 | ✅ Shortlisted |
| 2 | ... | ... | ... |

## Shortlisted Candidates — Detailed Analysis

### [Candidate Name] — Score: X/10
**Strengths:** ...
**Gaps:** ...
**Recommendation:** ...

[repeat for each shortlisted candidate]

## Interview Questions

### [Candidate Name]
1. [question]
2. [question]
...

## Final Recommendation
[Which candidate to prioritize and why. 2-3 sentences.]

---
*Generated by AI Hiring Assistant — Multi-Agent System*"""),

        HumanMessage(content=f"""
Role Summary: {state['role_summary']}
Required Skills: {', '.join(state['required_skills'])}
Preferred Skills: {', '.join(state['preferred_skills'])}
Experience: {state['experience_needed']}

All Candidates ({len(state['all_candidates'])} total):
{candidates_block}

Shortlisted ({len(shortlist_names)}): {', '.join(shortlist_names)}

Interview Questions:
{state['interview_questions']}

Write the full hiring report.
""")
    ])

    return {"hiring_report": response.content}
